import "./globals.css";
import { Inter } from "next/font/google";
import Link from "next/link";
import { GrFavorite, GrCart, GrLocation } from "react-icons/gr";
const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <header>
          <div className="aside_menu">
            <div>회원가입</div>
            <div>로그인</div>
            <div>고객센터</div>
          </div>
          <div className="main_menu">
            <Link href="/">
              <div className="logo_warp">
                <span>fresh</span>
              </div>
            </Link>
            <div className="search_warp">
              <input />
            </div>
            <div className="icon_warp">
              <span>
                <GrLocation />
              </span>
              <span>
                <GrFavorite />
              </span>
              <Link href="/cart">
                <span>
                  <GrCart />
                </span>
              </Link>
            </div>
          </div>
          <div className="sub_menu_warp">
            <Link href="/list">
              <div>카테고리</div>
            </Link>
            <ul>
              <li>신상품</li>
              <li>베스트</li>
              <li>특가/혜택</li>
            </ul>
            <div>샛별/배송안내</div>
          </div>
        </header>
        {children}
      </body>
    </html>
  );
}
